### ISSUE TITLE
Chain of dependencies

### ISSUE THREAD

**Issue by stigrj** [dev-cafe/parselglossy#76] opened 2019-07-09 08:28 UTC
### Description

The following chain of dependencies currently does not work if neither `bar` nor `baz` is set:
```
keywords:
  - name: foo                                                             
    type: float                                                                  
    docstring: "Foo"
  - name: bar
    type: float
    default: "user['foo']"
    docstring: "Bar"
  - name: baz
    type: float
    default: "user['bar']"
    docstring: "Baz"
```
It seems `baz` is first set equal to the string `"user['foo']"` (which is a type mismatch), *before* `bar` is set to the value of `foo`. Related to issue #73.

**Comment by bast** [comment] 2019-07-18 10:52
In a discussion with Stig and Roberto we are aiming at this:
- go through the template dictionary and build a dependency graph
- independent defaults and actions can be processed but dependent need to be postponed and processed in order
- dependency graph would also allow to detect cyclic dependencies upon which we would stop with an error

**Comment by robertodr** [comment] 2020-07-02 13:04
One solution we discussed is to reshuffle the tree (as extracted from `template.yml`) into a directed acyclic graph (DAG) using NetworkX. If there are circular dependencies, then there is no DAG and hence we error out.

Reminder to actually test for circular dependencies.

**Comment by bast** [comment] 2020-07-09 11:14
To check my understanding of the problem: We want to detect cyclic dependencies and abort at the generate step, right? So this is an error that only the code developer using parselglossy can see, but never the user of the code that uses the generated parser. Correct?

**Comment by robertodr** [comment] 2020-07-09 11:30
Correct. These are issues that happen in the `template.yml` specification and can be detected separately from any parsing, in https://github.com/dev-cafe/parselglossy/blob/dd57c64a278b0ba837743ab00fe24321cfda3342/parselglossy/validation.py#L89

I think that cycles can happen when:
1. A keyword's default depends on another keyword's default (Stig's example) From the template one can get a "simplified" dictionary with `view_by_default`.
2. A keyword's predicates depend on another keyword's value. From the template one can get a "simplified" dictionary with `view_by_predicates`.

**Comment by bast** [comment] 2020-07-09 12:25
Thanks! I experimented a bit with `networkx` and agree that this is the way to go and should not be too difficult.

**Comment by bast** [comment] 2020-07-09 14:33
Working on it ...

**Comment by robertodr** [comment] 2020-07-09 14:37
:hammer_and_wrench:

**Comment by bast** [comment] 2020-07-09 14:54
But right now the generator does not call any of these validators AFAICS - is this by design or by history?

**Comment by robertodr** [comment] 2020-07-09 14:59
It checks whether the template is valid with `is_template_valid`: https://github.com/dev-cafe/parselglossy/blob/master/parselglossy/api.py#L172-L179

**Comment by bast** [comment] 2020-07-09 15:02
Thanks! I was working in the wrong function (validate_from_dicts).

**Comment by bast** [comment] 2020-07-09 15:32
It's only now that I understand that these are really two issues. One is to sort the graph, and the other is to detect whether the graph is sortable.

**Comment by robertodr** [comment] 2020-07-15 08:47
#96 has been merged which solves the "degenerate" case of dependency chains. We'll be working on the "non-degenerate" case soon :hammer_and_wrench:

**Closed as completed** 2020-08-14 16:32 UTC
Labels: bug, enhancement
